### ISSUE TITLE
Errore al completamento del download di una stagione

### ISSUE THREAD

**Issue by atrasatti** [wetcork/raiplay-dl#1]
Quando scarico una stagione completa di una serie ricevuto sempre l'errore seguente:
```Traceback (most recent call last):
  File "/home/pi/raiplay-dl-main/raiplay-dl.py", line 430, in <module>
    main(args)
  File "/home/pi/raiplay-dl-main/raiplay-dl.py", line 35, in main
    pre_download_serie(data, args.seasons, args.episodes, args.format, args.out_dir)
  File "/home/pi/raiplay-dl-main/raiplay-dl.py", line 224, in pre_download_serie
    temp.append(seasons[int(i)-1])
IndexError: list index out of range
```

Per riprodurre basta fare una cosa tipo `python3 raiplay-dl.py https://www.raiplay.it/programmi/pimpa -s 3`.

Ho verificato con Python 3.9.2 su Bullseye e Python 3.8.2 su MacOS

**Comment by wetcork** [comment]
Ciao, scusa il ritardo nella risposta ma ero via, dovrebbe essere corretto ora, è una soluzione sbrigativa: il crash accade solo nel caso in cui le serie abbiano più "blocchi" (nel caso della serie della Pimpa se guardi nel sito c'è una sezione che sia chiama "Episodi" e "Episodi LIS").
Per il momento ho forzato lo script a scaricare solo i blocchi che si chiamino esattamente "Episodi" o "Puntate", in futuro andrebbe aggiunta una funzione per differenziare i tipi di blocchi e permettere il download di tutto.
