### ISSUE TITLE
Error dl avaiable formats

### ISSUE THREAD

**Issue by lmateovf** [wetcork/raiplay-dl#8]
Hi,
I've managed to get this link: http://creativemedia6-rai-it.akamaized.net/podcastcdn/teche_root/YT_ITALIA_TECHE_HD_multiaudio/13838144_5000.mp4
It corresponds to https://www.raiplay.it/video/2021/01/Che-Dio-ci-aiuti-S6E1-E-tu-sei-pronto-b4b77f3a-0496-4c99-95ab-097034450b02.html
But whenever I try to dl it, it always gives me a network error, even on different internet browser....

thanks in advance and I hope you can help me...

**Comment by lmateovf** [comment]
I got the link with this: https://greasyfork.org/es/scripts/2128-rai-play-video-download

**Comment by lmateovf** [comment]
On firefox: 
![Firefox](https://user-images.githubusercontent.com/62722086/222004563-36a117f7-8b11-4c5a-b547-061f6c14ae12.png)

**Comment by wetcork** [comment]
Are you streaming from italy or from another country?

**Comment by lmateovf** [comment]
I'm through VPN on Italy, Rome, not actually there, but it has allowed me to stream from their web without problem.

**Comment by wetcork** [comment]
Just tried to download the file myself and I also got an error so i think the file might be corrupted.

**Comment by lmateovf** [comment]
Yep, also if I try to dl the x_5000.mp4 or the x_2400.mp4 version it doens't work, only the x_1200,mp4 works...:
![imagen](https://user-images.githubusercontent.com/62722086/222561513-bff70bfa-a0ce-456a-bc6e-41cc4a0cf539.png)

Also, I must say that your script doesn't list any available quality for this episode at least...
Anyways, thank you in advance for your work.... I will stick to the 1200.mp4 version
Have a nice day!

**Comment by wetcork** [comment]
the script isn't woking at the moment, i'm actually rewriting the whole script from scratch for optimization and to add some other features so i'm gonna fix all the errors when i'll release the new version
